# prefix rebind
unbind C-Space
set -g prefix C-space
bind C-Space send-prefix

# enable mouse control
set -g mouse on

# reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded config"

# history limit
set-option -g history-limit 5000

# keep current path on new window
bind c new-window -c "#{pane_current_path}"

# panes
bind | split-window -h "#{pane_current_path}"
bind '\' split-window -v "#{pane_current_path}"
unbind '"'
unbind %
bind j choose-window 'join-pane -h -s "%%"'
bind J choose-window 'join-pane -s "%%"'

# Claude
bind-key h split-window -v -c "#{pane_current_path}" "claude"
set -g focus-events on
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'


### STYLING ###
# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=green'
# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'


### PLUGINS ###
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

# automatic tpm installation
if "test ! -d ~/.tmux/plugins/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'

